apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      affinity:
        podAntiAffinity:
          # requiredDuringSchedulingIgnoredDuringExecution:
          # - labelSelector:
          #     matchExpressions:
          #     - key: app
          #       operator: In
          #       values:
          #       - nginx
          #   topologyKey: "kubernetes.io/hostname"
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - nginx
              topologyKey: failure-domain.ford.com/zone
      dnsPolicy: ClusterFirst
      volumes:
        - name: nfs-volume
          persistentVolumeClaim:
            claimName: nginx-claim
      imagePullSecrets:
      - name: read-pull-secret  # <----- change this
      containers:
      - name: app-container
        image: ${IMAGE_REGISTRY}/${ORG_NAME}/${SUBDIR_LIST}:${IMAGE_TAG}
        imagePullPolicy: Always
        volumeMounts:
          - name: nfs-volume
            mountPath: /var/nfs
        ports:
          - name: http
            containerPort: 8080
        resources:
          requests:
            memory: "50Mi"
            cpu: "50m"
          limits:
            memory: "100Mi"
            cpu: "100m"
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 20
          #successThreshold: 1
          #failureThreshold: 10
          timeoutSeconds: 5
