apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-claim
#  labels:
#    demo: nfs-pv-provisioning
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 200Mi
  storageClassName: ${STORAGE_CLASS_NAME}
